using Beep.KocAiCommunity.Client;
using Beep.KocAiCommunity.Contracts.Admin;
using Beep.KocAiCommunity.Contracts.Community;
using Beep.KocAiCommunity.Contracts.Competitions;
using Beep.KocAiCommunity.Contracts.Connectors;
using Beep.KocAiCommunity.Contracts.Dashboard;
using Beep.KocAiCommunity.Contracts.Datasets;
using Beep.KocAiCommunity.Contracts.Engagement;
using Beep.KocAiCommunity.Contracts.Experiments;
using Beep.KocAiCommunity.Contracts.Help;
using Beep.KocAiCommunity.Contracts.Identity;
using Beep.KocAiCommunity.Contracts.Jobs;
using Beep.KocAiCommunity.Contracts.Learning;
using Beep.KocAiCommunity.Contracts.ML;
using Beep.KocAiCommunity.Contracts.Notifications;
using Beep.KocAiCommunity.Contracts.Platform;
using Beep.KocAiCommunity.Contracts.Studio;
using Beep.KocAiCommunity.Contracts.Supervision;
using Beep.KocAiCommunity.Contracts.Workflow;
using ExperimentRunDto = Beep.KocAiCommunity.Contracts.Experiments.RunDto;
using RunDto = Beep.KocAiCommunity.Contracts.Jobs.RunDto;

namespace Beep.KocAiCommunity.Desktop.Local;

/// <summary>
/// Implements the full <see cref="IKocApiClient"/> by delegating every call to an inner HTTP
/// client. <see cref="LocalKocApiClient"/> derives from this and overrides only the Studio
/// methods to run in-process (offline); everything else (competitions, /me, …) flows to the API.
/// </summary>
public abstract class RemoteFallbackKocApiClient(IKocApiClient remote) : IKocApiClient
{
    protected IKocApiClient Remote => remote;

    public virtual Task<PlatformMetaDto?> GetPlatformMetaAsync(CancellationToken ct = default) => remote.GetPlatformMetaAsync(ct);
    public virtual Task<MeResponse?> GetMeAsync(CancellationToken ct = default) => remote.GetMeAsync(ct);
    public virtual Task<AssignableRolesDto?> GetAssignableRolesAsync(CancellationToken ct = default) => remote.GetAssignableRolesAsync(ct);
    public virtual Task<IReadOnlyList<CompetitionCategoryDto>> GetCompetitionCategoriesAsync(CancellationToken ct = default) => remote.GetCompetitionCategoriesAsync(ct);
    public virtual Task<IReadOnlyList<CompetitionCategoryDto>> GetAdminCompetitionCategoriesAsync(CancellationToken ct = default) => remote.GetAdminCompetitionCategoriesAsync(ct);
    public virtual Task<string?> UpsertCompetitionCategoryAsync(UpsertCompetitionCategoryRequest request, CancellationToken ct = default) => remote.UpsertCompetitionCategoryAsync(request, ct);
    public virtual Task<string?> DeleteCompetitionCategoryAsync(string code, CancellationToken ct = default) => remote.DeleteCompetitionCategoryAsync(code, ct);
    public virtual Task<string?> SetCompetitionCategoryAsync(Guid competitionId, string? code, CancellationToken ct = default) => remote.SetCompetitionCategoryAsync(competitionId, code, ct);
    public virtual Task<IReadOnlyList<LearningLinkDto>> GetLearningLinksAsync(CancellationToken ct = default) => remote.GetLearningLinksAsync(ct);
    public virtual Task<string?> SetTrackRecommendedCompetitionAsync(Guid trackId, Guid? competitionId, CancellationToken ct = default) => remote.SetTrackRecommendedCompetitionAsync(trackId, competitionId, ct);
    public virtual Task<string?> SetCompetitionRecommendedTrackAsync(Guid competitionId, Guid? trackId, CancellationToken ct = default) => remote.SetCompetitionRecommendedTrackAsync(competitionId, trackId, ct);
    public virtual Task<string?> SetUserRolesAsync(string userId, IReadOnlyList<string> roles, CancellationToken ct = default) => remote.SetUserRolesAsync(userId, roles, ct);
    public virtual Task<string?> SetUserPositionAsync(string userId, string position, CancellationToken ct = default) => remote.SetUserPositionAsync(userId, position, ct);
    public virtual Task<(AuthTokenResponse? Auth, string? Error)> RegisterAsync(RegisterRequest request, CancellationToken ct = default) => remote.RegisterAsync(request, ct);
    public virtual Task<(AuthTokenResponse? Auth, string? Error)> LoginAsync(LoginRequest request, CancellationToken ct = default) => remote.LoginAsync(request, ct);
    public virtual Task<RegistrationStateResponse?> GetRegistrationStateAsync(CancellationToken ct = default) => remote.GetRegistrationStateAsync(ct);
    public virtual Task<IReadOnlyList<TrackDto>> GetTracksAsync(CancellationToken ct = default) => remote.GetTracksAsync(ct);
    public virtual Task<TrackDetailDto?> GetTrackAsync(Guid trackId, CancellationToken ct = default) => remote.GetTrackAsync(trackId, ct);
    public virtual Task EnrollAsync(Guid trackId, CancellationToken ct = default) => remote.EnrollAsync(trackId, ct);
    public virtual Task CompleteLessonAsync(Guid trackId, Guid lessonId, CancellationToken ct = default) => remote.CompleteLessonAsync(trackId, lessonId, ct);
    public virtual Task<IReadOnlyList<MyLearningDto>> GetMyLearningAsync(CancellationToken ct = default) => remote.GetMyLearningAsync(ct);
    public virtual Task<IReadOnlyList<CompetitionDto>> GetCompetitionsAsync(CancellationToken ct = default) => remote.GetCompetitionsAsync(ct);
    public virtual Task<PublicShowcaseDto> GetPublicShowcaseAsync(CancellationToken ct = default) => remote.GetPublicShowcaseAsync(ct);
    public virtual Task<CompetitionDto?> GetCompetitionAsync(Guid competitionId, CancellationToken ct = default) => remote.GetCompetitionAsync(competitionId, ct);
    public virtual Task<CompetitionDto?> CreateCompetitionAsync(CreateCompetitionRequest request, CancellationToken ct = default) => remote.CreateCompetitionAsync(request, ct);
    public virtual Task SetAnswerKeyAsync(Guid competitionId, Stream csv, string fileName, CancellationToken ct = default) => remote.SetAnswerKeyAsync(competitionId, csv, fileName, ct);
    public virtual Task<SubmissionResultDto?> SubmitAsync(Guid competitionId, Stream csv, string fileName, CancellationToken ct = default) => remote.SubmitAsync(competitionId, csv, fileName, ct);
    public virtual Task<SubmissionResultDto?> SubmitPipelineAsync(Guid competitionId, WorkflowDefinition definition, CancellationToken ct = default) => remote.SubmitPipelineAsync(competitionId, definition, ct);
    public virtual Task SetCompetitionDatasetsAsync(Guid competitionId, Stream training, Stream evaluation, string labelColumn, string idColumn, string task, CancellationToken ct = default) => remote.SetCompetitionDatasetsAsync(competitionId, training, evaluation, labelColumn, idColumn, task, ct);
    public virtual Task<string?> GetCompetitionDataAsync(Guid competitionId, string which, CancellationToken ct = default) => remote.GetCompetitionDataAsync(competitionId, which, ct);
    public virtual Task<IReadOnlyList<SubmissionResultDto>> GetMySubmissionsAsync(Guid competitionId, CancellationToken ct = default) => remote.GetMySubmissionsAsync(competitionId, ct);
    public virtual Task<IReadOnlyList<LeaderboardEntryDto>> GetLeaderboardAsync(Guid competitionId, CancellationToken ct = default) => remote.GetLeaderboardAsync(competitionId, ct);
    public virtual Task<IReadOnlyList<NotificationDto>> GetNotificationsAsync(bool unreadOnly = false, int take = 30, CancellationToken ct = default) => remote.GetNotificationsAsync(unreadOnly, take, ct);
    public virtual Task<int> GetUnreadNotificationCountAsync(CancellationToken ct = default) => remote.GetUnreadNotificationCountAsync(ct);
    public virtual Task MarkNotificationReadAsync(Guid id, CancellationToken ct = default) => remote.MarkNotificationReadAsync(id, ct);
    public virtual Task MarkAllNotificationsReadAsync(CancellationToken ct = default) => remote.MarkAllNotificationsReadAsync(ct);
    public virtual Task SetCompetitionStatusAsync(Guid competitionId, string status, CancellationToken ct = default) => remote.SetCompetitionStatusAsync(competitionId, status, ct);
    public virtual Task SetCompetitionFeaturedAsync(Guid competitionId, CancellationToken ct = default) => remote.SetCompetitionFeaturedAsync(competitionId, ct);
    public virtual Task SetCompetitionPrizesAsync(Guid competitionId, SetPrizesRequest request, CancellationToken ct = default) => remote.SetCompetitionPrizesAsync(competitionId, request, ct);
    public virtual Task SetCompetitionHeroImagePathAsync(Guid competitionId, string? path, CancellationToken ct = default) => remote.SetCompetitionHeroImagePathAsync(competitionId, path, ct);
    public virtual Task SetCompetitionRevealAsync(Guid competitionId, DateTime? revealUtc, CancellationToken ct = default) => remote.SetCompetitionRevealAsync(competitionId, revealUtc, ct);
    public virtual Task<IReadOnlyList<LeaderboardEntryDto>?> GetFinalLeaderboardAsync(Guid competitionId, CancellationToken ct = default) => remote.GetFinalLeaderboardAsync(competitionId, ct);
    public virtual Task<SupervisionRollupDto?> GetSupervisionRollupAsync(CancellationToken ct = default) => remote.GetSupervisionRollupAsync(ct);
    public virtual Task<PersonalDashboardDto?> GetPersonalDashboardAsync(CancellationToken ct = default) => remote.GetPersonalDashboardAsync(ct);
    public virtual Task<IReadOnlyList<DatasetDto>> GetDatasetsAsync(CancellationToken ct = default) => remote.GetDatasetsAsync(ct);
    public virtual Task<DatasetDto?> CreateDatasetAsync(CreateDatasetRequest request, CancellationToken ct = default) => remote.CreateDatasetAsync(request, ct);
    public virtual Task<VisibilityOptionDto?> GetAudienceAsync(string scope, CancellationToken ct = default) => remote.GetAudienceAsync(scope, ct);
    public virtual Task<IReadOnlyList<DatasetVersionDto>> GetDatasetVersionsAsync(Guid datasetId, CancellationToken ct = default) => remote.GetDatasetVersionsAsync(datasetId, ct);
    public virtual Task<DatasetVersionDetailDto?> GetDatasetVersionAsync(Guid datasetId, int versionNumber, CancellationToken ct = default) => remote.GetDatasetVersionAsync(datasetId, versionNumber, ct);
    public virtual Task<(DatasetVersionDto? Version, string? Error)> UploadDatasetFileAsync(Guid datasetId, Stream content, string fileName, CancellationToken ct = default) => remote.UploadDatasetFileAsync(datasetId, content, fileName, ct);
    public virtual Task<(DatasetVersionDto? Version, string? Error)> ImportDatasetUrlAsync(Guid datasetId, string url, CancellationToken ct = default) => remote.ImportDatasetUrlAsync(datasetId, url, ct);
    public virtual Task<string?> PublishDatasetVersionAsync(Guid datasetId, int versionNumber, CancellationToken ct = default) => remote.PublishDatasetVersionAsync(datasetId, versionNumber, ct);
    public virtual string DatasetFileDownloadUrl(Guid fileId) => remote.DatasetFileDownloadUrl(fileId);
    public virtual Task<ModelRunDto?> TrainAsync(Stream csv, string fileName, string labelColumn, string datasetName, string task, CancellationToken ct = default) => remote.TrainAsync(csv, fileName, labelColumn, datasetName, task, ct);
    public virtual Task<(ModelRunDto? Run, string? Error)> TrainFromDatasetAsync(Guid datasetId, string labelColumn, string task, CancellationToken ct = default) => remote.TrainFromDatasetAsync(datasetId, labelColumn, task, ct);
    public virtual Task<IReadOnlyList<ModelRunDto>> GetModelRunsAsync(CancellationToken ct = default) => remote.GetModelRunsAsync(ct);
    public virtual Task<IReadOnlyList<DiscussionDto>> GetDiscussionsAsync(CancellationToken ct = default) => remote.GetDiscussionsAsync(ct);
    public virtual Task<DiscussionDto?> CreateDiscussionAsync(CreateDiscussionRequest request, CancellationToken ct = default) => remote.CreateDiscussionAsync(request, ct);
    public virtual Task<DiscussionDetailDto?> GetDiscussionAsync(Guid id, CancellationToken ct = default) => remote.GetDiscussionAsync(id, ct);
    public virtual Task<ReplyDto?> AddReplyAsync(Guid discussionId, string body, CancellationToken ct = default) => remote.AddReplyAsync(discussionId, body, ct);
    public virtual Task<IReadOnlyList<ReactionDto>> ReactToDiscussionAsync(Guid id, string emoji, CancellationToken ct = default) => remote.ReactToDiscussionAsync(id, emoji, ct);
    public virtual Task<IReadOnlyList<ReactionDto>> ReactToReplyAsync(Guid discussionId, Guid replyId, string emoji, CancellationToken ct = default) => remote.ReactToReplyAsync(discussionId, replyId, emoji, ct);
    public virtual Task<string?> SetDiscussionLockAsync(Guid id, bool locked, CancellationToken ct = default) => remote.SetDiscussionLockAsync(id, locked, ct);
    public virtual Task<string?> SetDiscussionPinAsync(Guid id, bool pinned, CancellationToken ct = default) => remote.SetDiscussionPinAsync(id, pinned, ct);
    public virtual Task<string?> DeleteDiscussionAsync(Guid id, CancellationToken ct = default) => remote.DeleteDiscussionAsync(id, ct);
    public virtual Task<string?> DeleteReplyAsync(Guid discussionId, Guid replyId, CancellationToken ct = default) => remote.DeleteReplyAsync(discussionId, replyId, ct);
    public virtual Task<IReadOnlyList<MentionCandidateDto>> SearchMentionCandidatesAsync(string q, CancellationToken ct = default) => remote.SearchMentionCandidatesAsync(q, ct);
    public virtual Task<(AttachmentDto? Attachment, string? Error)> AddAttachmentAsync(Guid discussionId, Stream content, string fileName, CancellationToken ct = default) => remote.AddAttachmentAsync(discussionId, content, fileName, ct);
    public virtual Task<WorkflowValidationResult?> ValidateWorkflowAsync(WorkflowDefinition definition, CancellationToken ct = default) => remote.ValidateWorkflowAsync(definition, ct);
    public virtual Task<ModelRunDto?> RunWorkflowAsync(WorkflowDefinition definition, Stream csv, string fileName, string labelColumn, CancellationToken ct = default) => remote.RunWorkflowAsync(definition, csv, fileName, labelColumn, ct);
    public virtual Task<PipelineExecutionResult?> ExecuteWorkflowAsync(WorkflowDefinition definition, Stream csv, string fileName, string labelColumn, string task, CancellationToken ct = default) => remote.ExecuteWorkflowAsync(definition, csv, fileName, labelColumn, task, ct);
    public virtual Task<(PipelineExecutionResult? Result, string? Error)> ExecuteWorkflowFromDatasetAsync(WorkflowDefinition definition, Guid datasetId, string labelColumn, string task, CancellationToken ct = default) => remote.ExecuteWorkflowFromDatasetAsync(definition, datasetId, labelColumn, task, ct);
    public virtual Task<IReadOnlyList<ConnectorDescriptorDto>> GetConnectorsAsync(CancellationToken ct = default) => remote.GetConnectorsAsync(ct);
    public virtual Task<IReadOnlyList<ConnectorInstanceDto>> GetConnectorInstancesAsync(string code, CancellationToken ct = default) => remote.GetConnectorInstancesAsync(code, ct);
    public virtual Task<(ConnectorInstanceDto? Instance, string? Error)> CreateConnectorInstanceAsync(string code, CreateConnectorInstanceRequest request, CancellationToken ct = default) => remote.CreateConnectorInstanceAsync(code, request, ct);
    public virtual Task<ConnectorInstanceDetailDto?> GetConnectorInstanceAsync(Guid id, CancellationToken ct = default) => remote.GetConnectorInstanceAsync(id, ct);
    public virtual Task<(CredentialInfoDto? Credential, string? Error)> SetConnectorCredentialAsync(Guid id, SetCredentialRequest request, CancellationToken ct = default) => remote.SetConnectorCredentialAsync(id, request, ct);
    public virtual Task<(ConnectorTestDto? Result, string? Error)> TestConnectorAsync(Guid id, CancellationToken ct = default) => remote.TestConnectorAsync(id, ct);
    public virtual Task<(ConnectorHealthDto? Health, string? Error)> ProbeConnectorHealthAsync(Guid id, CancellationToken ct = default) => remote.ProbeConnectorHealthAsync(id, ct);
    public virtual Task<ConnectorSchemaDto?> GetConnectorSchemaAsync(Guid id, CancellationToken ct = default) => remote.GetConnectorSchemaAsync(id, ct);
    public virtual Task<string?> DeleteConnectorInstanceAsync(Guid id, CancellationToken ct = default) => remote.DeleteConnectorInstanceAsync(id, ct);
    public virtual Task<IReadOnlyList<HelpArticleSummaryDto>> GetHelpArticlesAsync(string? category = null, string? q = null, CancellationToken ct = default) => remote.GetHelpArticlesAsync(category, q, ct);
    public virtual Task<HelpArticleDto?> GetHelpArticleAsync(string slug, CancellationToken ct = default) => remote.GetHelpArticleAsync(slug, ct);
    public virtual Task<IReadOnlyList<NodeDescriptorDto>> GetMlNodesAsync(CancellationToken ct = default) => remote.GetMlNodesAsync(ct);
    public virtual Task<IReadOnlyList<MlTaskDto>> GetMlTasksAsync(CancellationToken ct = default) => remote.GetMlTasksAsync(ct);
    public virtual Task<AdminDashboardDto?> GetAdminDashboardAsync(CancellationToken ct = default) => remote.GetAdminDashboardAsync(ct);
    public virtual Task<IReadOnlyList<SettingDto>> GetSettingsAsync(CancellationToken ct = default) => remote.GetSettingsAsync(ct);
    public virtual Task<(SettingDto? Setting, string? Error)> UpdateSettingAsync(string key, string value, CancellationToken ct = default) => remote.UpdateSettingAsync(key, value, ct);
    public virtual Task<IReadOnlyList<FeatureFlagDto>> GetFeatureFlagsAsync(CancellationToken ct = default) => remote.GetFeatureFlagsAsync(ct);
    public virtual Task<(FeatureFlagDto? Flag, string? Error)> UpsertFeatureFlagAsync(string key, UpsertFeatureFlagRequest request, CancellationToken ct = default) => remote.UpsertFeatureFlagAsync(key, request, ct);
    public virtual Task<IReadOnlyList<AuditLogDto>> GetAuditAsync(string? action = null, CancellationToken ct = default) => remote.GetAuditAsync(action, ct);
    public virtual Task<DemoDataStatusDto?> GetDemoStatusAsync(CancellationToken ct = default) => remote.GetDemoStatusAsync(ct);
    public virtual Task<(DemoDataStatusDto? Status, string? Error)> SeedDemoAsync(CancellationToken ct = default) => remote.SeedDemoAsync(ct);
    public virtual Task<(DemoDataStatusDto? Status, string? Error)> UnseedDemoAsync(CancellationToken ct = default) => remote.UnseedDemoAsync(ct);
    public virtual Task<IReadOnlyList<AdminUserDto>> GetAdminUsersAsync(CancellationToken ct = default) => remote.GetAdminUsersAsync(ct);
    public virtual Task<IReadOnlyList<OrgUnitCodeDto>> GetAdminOrgUnitsAsync(CancellationToken ct = default) => remote.GetAdminOrgUnitsAsync(ct);
    public virtual Task<(AdminUserDto? User, string? Error)> UpsertUserProfileAsync(string userId, UpsertUserProfileRequest request, CancellationToken ct = default) => remote.UpsertUserProfileAsync(userId, request, ct);
    public virtual Task<string?> SetCompetitionGrantAsync(string userId, string maxScope, CancellationToken ct = default) => remote.SetCompetitionGrantAsync(userId, maxScope, ct);
    public virtual Task<string?> RevokeCompetitionGrantAsync(string userId, CancellationToken ct = default) => remote.RevokeCompetitionGrantAsync(userId, ct);
    public virtual Task<string?> SetOrgUnitCodeAsync(Guid orgUnitId, string? code, CancellationToken ct = default) => remote.SetOrgUnitCodeAsync(orgUnitId, code, ct);
    public virtual Task<IReadOnlyList<WorkflowSummaryDto>> GetWorkflowsAsync(CancellationToken ct = default) => remote.GetWorkflowsAsync(ct);
    public virtual Task<(WorkflowSummaryDto? Workflow, string? Error)> CreateWorkflowAsync(CreateWorkflowRequest request, CancellationToken ct = default) => remote.CreateWorkflowAsync(request, ct);
    public virtual Task<WorkflowDetailDto?> GetWorkflowDetailAsync(Guid id, CancellationToken ct = default) => remote.GetWorkflowDetailAsync(id, ct);
    public virtual Task<WorkflowVersionDetailDto?> GetWorkflowVersionAsync(Guid id, int versionNumber, CancellationToken ct = default) => remote.GetWorkflowVersionAsync(id, versionNumber, ct);
    public virtual Task<(WorkflowVersionDto? Version, string? Error)> SaveWorkflowDraftAsync(Guid id, SaveDraftRequest request, CancellationToken ct = default) => remote.SaveWorkflowDraftAsync(id, request, ct);
    public virtual Task<string?> DeleteWorkflowAsync(Guid id, CancellationToken ct = default) => remote.DeleteWorkflowAsync(id, ct);
    public virtual Task<string?> PublishWorkflowVersionAsync(Guid id, int versionNumber, CancellationToken ct = default) => remote.PublishWorkflowVersionAsync(id, versionNumber, ct);
    public virtual Task<string?> ArchiveWorkflowVersionAsync(Guid id, int versionNumber, CancellationToken ct = default) => remote.ArchiveWorkflowVersionAsync(id, versionNumber, ct);
    public virtual Task<(Guid? RunId, string? Error)> RunWorkflowVersionAsync(Guid id, int versionNumber, RunWorkflowVersionRequest request, CancellationToken ct = default) => remote.RunWorkflowVersionAsync(id, versionNumber, request, ct);
    public virtual Task<WorkflowExportDto?> ExportWorkflowVersionAsync(Guid id, int versionNumber, CancellationToken ct = default) => remote.ExportWorkflowVersionAsync(id, versionNumber, ct);
    public virtual Task<(WorkflowSummaryDto? Workflow, string? Error)> ImportWorkflowAsync(ImportWorkflowRequest request, CancellationToken ct = default) => remote.ImportWorkflowAsync(request, ct);
    public virtual Task<IReadOnlyList<WorkflowTemplateDto>> GetWorkflowTemplatesAsync(CancellationToken ct = default) => remote.GetWorkflowTemplatesAsync(ct);
    public virtual Task<(WorkflowSummaryDto? Workflow, string? Error)> InstantiateTemplateAsync(string code, InstantiateTemplateRequest request, CancellationToken ct = default) => remote.InstantiateTemplateAsync(code, request, ct);
    public virtual Task<IReadOnlyList<RegisteredModelDto>> GetModelsAsync(CancellationToken ct = default) => remote.GetModelsAsync(ct);
    public virtual Task<ModelVersionDto?> RegisterModelAsync(RegisterModelRequest request, CancellationToken ct = default) => remote.RegisterModelAsync(request, ct);
    public virtual Task<string?> ApproveVersionAsync(Guid versionId, CancellationToken ct = default) => remote.ApproveVersionAsync(versionId, ct);
    public virtual Task<string?> PromoteVersionAsync(Guid versionId, CancellationToken ct = default) => remote.PromoteVersionAsync(versionId, ct);
    public virtual Task<string?> RollbackVersionAsync(Guid versionId, CancellationToken ct = default) => remote.RollbackVersionAsync(versionId, ct);
    public virtual Task<string?> DeployVersionAsync(Guid versionId, CancellationToken ct = default) => remote.DeployVersionAsync(versionId, ct);
    public virtual Task<string?> RetireDeploymentAsync(Guid deploymentId, CancellationToken ct = default) => remote.RetireDeploymentAsync(deploymentId, ct);
    public virtual Task<IReadOnlyList<DeploymentDto>> GetDeploymentsAsync(CancellationToken ct = default) => remote.GetDeploymentsAsync(ct);
    public virtual Task<(InferResponseDto? Result, string? Error)> InferAsync(Guid versionId, IReadOnlyDictionary<string, string> input, CancellationToken ct = default) => remote.InferAsync(versionId, input, ct);
    public virtual Task<(InferResponseDto? Result, string? Error)> InferBatchAsync(Guid versionId, IReadOnlyList<IReadOnlyDictionary<string, string>> rows, CancellationToken ct = default) => remote.InferBatchAsync(versionId, rows, ct);
    public virtual Task<IReadOnlyList<InferenceLogDto>> GetInferenceLogsAsync(Guid versionId, CancellationToken ct = default) => remote.GetInferenceLogsAsync(versionId, ct);
    public virtual Task<(DriftReportDto? Report, string? Error)> ComputeDriftAsync(Guid versionId, IReadOnlyList<IReadOnlyDictionary<string, string>> rows, CancellationToken ct = default) => remote.ComputeDriftAsync(versionId, rows, ct);
    public virtual Task<ProfileDto?> GetMyProfileAsync(CancellationToken ct = default) => remote.GetMyProfileAsync(ct);
    public virtual Task<ProfileDto?> GetProfileAsync(string userId, CancellationToken ct = default) => remote.GetProfileAsync(userId, ct);
    public virtual Task<ProfileDto?> UpdateProfileAsync(UpdateProfileRequest request, CancellationToken ct = default) => remote.UpdateProfileAsync(request, ct);
    public virtual Task<IReadOnlyList<XpLeaderboardRowDto>> GetXpLeaderboardAsync(string period, CancellationToken ct = default) => remote.GetXpLeaderboardAsync(period, ct);
    public virtual Task<IReadOnlyList<TeamLeaderboardRowDto>> GetTeamLeaderboardAsync(string period, CancellationToken ct = default) => remote.GetTeamLeaderboardAsync(period, ct);
    public virtual Task<IReadOnlyList<BadgeDto>> GetBadgeCatalogAsync(CancellationToken ct = default) => remote.GetBadgeCatalogAsync(ct);
    public virtual Task<IReadOnlyList<string>> GetAvatarIconsAsync(CancellationToken ct = default) => remote.GetAvatarIconsAsync(ct);
    public virtual Task<string?> GiveKudosAsync(GiveKudosRequest request, CancellationToken ct = default) => remote.GiveKudosAsync(request, ct);
    public virtual Task<IReadOnlyList<KudosDto>> GetKudosAsync(string userId, CancellationToken ct = default) => remote.GetKudosAsync(userId, ct);
    public virtual Task<IReadOnlyList<ActivityDto>> GetActivityAsync(CancellationToken ct = default) => remote.GetActivityAsync(ct);
    public virtual Task<IReadOnlyList<RunDto>> GetRunsAsync(CancellationToken ct = default) => remote.GetRunsAsync(ct);
    public virtual Task<RunDto?> GetRunAsync(Guid id, CancellationToken ct = default) => remote.GetRunAsync(id, ct);
    public virtual Task<RunDto?> CreateRunAsync(CreateRunRequest request, CancellationToken ct = default) => remote.CreateRunAsync(request, ct);
    public virtual Task CancelRunAsync(Guid id, CancellationToken ct = default) => remote.CancelRunAsync(id, ct);
    public virtual Task<IReadOnlyList<RunLogDto>> GetRunLogsAsync(Guid id, CancellationToken ct = default) => remote.GetRunLogsAsync(id, ct);
    public virtual Task<IReadOnlyList<RunAttemptDto>> GetRunAttemptsAsync(Guid id, CancellationToken ct = default) => remote.GetRunAttemptsAsync(id, ct);
    public virtual Task<IReadOnlyList<ExperimentDto>> GetExperimentsAsync(CancellationToken ct = default) => remote.GetExperimentsAsync(ct);
    public virtual Task<ExperimentDto?> CreateExperimentAsync(CreateExperimentRequest request, CancellationToken ct = default) => remote.CreateExperimentAsync(request, ct);
    public virtual Task<IReadOnlyList<ExperimentRunDto>> GetExperimentRunsAsync(Guid experimentId, CancellationToken ct = default) => remote.GetExperimentRunsAsync(experimentId, ct);
    public virtual Task<IReadOnlyList<ComparisonRowDto>> GetExperimentCompareAsync(Guid experimentId, CancellationToken ct = default) => remote.GetExperimentCompareAsync(experimentId, ct);
    public virtual Task<IReadOnlyList<RunMetricDto>> GetRunMetricsAsync(Guid runId, CancellationToken ct = default) => remote.GetRunMetricsAsync(runId, ct);
    public virtual Task<IReadOnlyList<RunParameterDto>> GetRunParametersAsync(Guid runId, CancellationToken ct = default) => remote.GetRunParametersAsync(runId, ct);
    public virtual Task<ExperimentRunDto?> UpdateExperimentRunAsync(Guid runId, UpdateRunRequest request, CancellationToken ct = default) => remote.UpdateExperimentRunAsync(runId, request, ct);
    public virtual Task<(ModelVersionDto? Version, string? Error)> RegisterExperimentRunAsync(Guid runId, string modelName, CancellationToken ct = default) => remote.RegisterExperimentRunAsync(runId, modelName, ct);
}
